// Code generated by "stringer -type=ManagerType -linecomment"; DO NOT EDIT.

package license

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ManagerTypeACSM-1]
	_ = x[ManagerTypeAMS2-2]
	_ = x[ManagerTypePCars2-3]
	_ = x[ManagerTypeACC-4]
	_ = x[ManagerTypeAny-5]
}

const _ManagerType_name = "Assetto Corsa Server ManagerAutomobilista 2 Server ManagerProject Cars 2 Server ManagerAssetto Corsa Competizione Server ManagerAny Server Manager"

var _ManagerType_index = [...]uint8{0, 28, 58, 87, 128, 146}

func (i ManagerType) String() string {
	i -= 1
	if i < 0 || i >= ManagerType(len(_ManagerType_index)-1) {
		return "ManagerType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ManagerType_name[_ManagerType_index[i]:_ManagerType_index[i+1]]
}
